### PR TITLE
land the initial puppet pyup docs

### PR DESCRIPTION
**Pull request by escapewindow**
These can grow over time, but hopefully this is a good start.

I also fixed the spelling of `accessing`. If we don't want that I can drop it from the PR.

### CODE REVIEW

**Comment by escapewindow** [comment]
@lundjordan , @Callek , @srfraser thoughts?

**Comment by lundjordan** [comment]
Wow, this is great. Really great breaking things down by what's expected and what can often go wrong. I've asked CIDuty to read through this too so they are familiar with the work involved for all of us.

**Comment by srfraser** [comment]
This is really good! For the module download races, I wonder what the implications would be if the module downloader also examined open pull requests

**Comment by escapewindow** [comment]
> This is really good! For the module download races, I wonder what the implications would be if the module downloader also examined open pull requests

Possible. I was also thinking we could update puppet into a staging area, download the new packages, and then update the production puppet configs once the download happened successfully.

How much time we want to spend improving things probably depends on how soon we can get off puppet and onto docker images :)

**Pull request merged**
