### PR TITLE
Updates to the CHANGELOG to reflect the recent GCP changes

### PR DESCRIPTION
**Pull request by MihaiTabara**

### CODE REVIEW

**Comment by MihaiTabara** [comment]
I realized today that we don't yet have a better home to track these changes that affect releaseduty. Until we find a better home, I still believe there's value in tracking them here. Was there anything else that happened in the last 70-71 notable of mentioning? (I'm thinking of the signing changes: e.g. retirement of the signing-servers, full switch to Autograph, etc)

**Comment by escapewindow** [comment]
in progress changes:

- l10n bumper for central is moving to taskcluster cron shortly; will uplift to beta and esr68 later
- signing servers are being shut down. we've already stopped using them, however.

**Comment by escapewindow** [comment]
completed:
- Treescript has been refactored.
- scriptworker-scripts docker images now mount the repo at /app instead of the script. (we may revisit this to lower disk usage)

**Comment by MihaiTabara** [comment]
@escapewindow piggy-backed your comments in the changelog too, thanks for pointing them out

**Pull request merged**
