### PR TITLE
Update mergeday docs to reflect the current state of ESR68

### PR DESCRIPTION
**Pull request by JohanLorenzo**
This may not be needed anymore thanks to https://bugzilla.mozilla.org/show_bug.cgi?id=1562629. ESR68-scripts haven't landed on central because [this discussion](https://phabricator.services.mozilla.com/D37396#1119622) is still up in the air. What do you think we should do next, @tomprince ?

### CODE REVIEW

**Comment by lundjordan** [comment]
@tomprince @JohanLorenzo what should we do here?

**Comment by lundjordan** [comment]
I also see: [Bug 1562629](https://bugzilla.mozilla.org/show_bug.cgi?id=1562629) - Bump the ESR minor version number (i.e. 68.x -> 68.y) at the start of the cycle

**Comment by JohanLorenzo** [comment]
Thanks @lundjordan for digging this PR up 🙂

[Bug 1562629](https://bugzilla.mozilla.org/show_bug.cgi?id=1562629) hasn't moved since [my first comment](https://github.com/mozilla-releng/releasewarrior-2.0/pull/234#issue-313234980) (in this PR). 

> ESR68-scripts haven't landed on central because this discussion is still up in the air. 

Same here. 


Therefore, I think we should land this PR as is. It contains the most up-to-date instructions.

**Comment by lundjordan** [comment]
@JohanLorenzo - okay so main thing is moving esr bump to week after merge day along side central bump. And to use a different mozharness checkout to do it? wfm, if so.

**Comment by JohanLorenzo** [comment]
> @JohanLorenzo - okay so main thing is moving esr bump to week after merge day along side central bump. And to use a different mozharness checkout to do it? wfm, if so.

That's right! 👍

**Pull request merged**
